site_name: The Almost Engineer
site_url: https://thealmostengineer.com
site_description: The blog of Kenny Robinson
site_author: Kenny Robinson, @almostengr
copyright: Copyright &copy; 2010-2022 Kenny Robinson

# repository information
# repo_url: https://github.com/almostengr/almostengrwebsite
# repo_name: almostengrwebsite
remote_name: origin
remote_branch: website

# Development server details
dev_addr: 192.168.1.103:8000

# Appearance
theme:
  name: material
  custom_dir: 'theme-overrides'
  language: en
  static_templates:
    - 404.html
  font:
    text: Ubuntu
    code: Ubuntu Mono
  palette:
    - scheme: default
      primary: black
      accent: red
  # favicon: /images/favicon-32x32.png
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - toc.integrate
    - navigation.top
    # - navigation.expand
    - navigation.tracking

  # courses:
  #   - url: https://www.youtube.com/watch?v=iujOWWbiUP0&list=PLaAJ0fv0d9WM8E2K_Ke5As-fw626yQ3tu
  #     body: Learning the basics of Drupal 8 is easy. Watch the free course now!
  #     title: Drupal 8 Course

use_directory_urls: true
strict: false

plugins:
  - minify:
      minify_html: true
  - search:
      lang: en
      min_search_length: 3

extra: 
  analytics:
    provider: google  
    property: 
  social: 
    - icon: fontawesome/brands/github 
      link: https://github.com/almostengr
      name: almostengr on Github
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/almostengr
      name: "@almostengr on Instagram"
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/almostengr
      name: "@almostengr on Twitter"
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/c/RobinsonHandyandTechnologyServices?sub_confirmation=1
      name: Robinson Handy and Technology Services on YouTube
      
