name: Site Map Ping

on:
  schedule:
    - cron: '15 06 * * 5'

jobs:
  sitemapush:
    runs-on: ubuntu-latest

    steps:
    - name: Sitemap Ping to search engines
      uses: atymic/sitemap-ping-action@1.1.0
      with:
        sitemap-url: https://thealmostengineer.com/sitemap.xml
        
